from django.contrib import admin
from .models import *

admin.site.register(Pais)
admin.site.register(Departamentos)
# admin.site.register(Colmena)
# admin.site.register(Estanque)
# admin.site.register(Ciudad)
# admin.site.register(Persona)
# admin.site.register(Contrato)
# admin.site.register(Cultivo)
# admin.site.register(Departamentos)
# admin.site.register(Direccion)
# admin.site.register(InfotrataColmena)
# admin.site.register(InfotrataEstanque)
# admin.site.register(MSensorColmena)
# admin.site.register(MSensorEstanque)
# admin.site.register(Pais)
# admin.site.register(Colmena)
# admin.site.register(Sensor)
# admin.site.register(TEmpresa)
# admin.site.register(TIdentificacion)
# admin.site.register(Tiptrata)
# admin.site.register(Tratamiento)
# admin.site.register(Tsensor)
