# Generated by Django 4.2.2 on 2023-08-11 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='correo',
            field=models.CharField(db_comment='correo usado para ponerse en contacto con la persona', max_length=120, null=True),
        ),
    ]
