# Generated by Django 4.2.1 on 2023-08-05 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_persona_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='telefono',
            field=models.CharField(db_comment='telefono usado para ponerse en contacto con la persona', max_length=120),
        ),
    ]
