# Generated by Django 4.2.1 on 2023-08-05 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_alter_persona_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infotratacolmena',
            old_name='nombre',
            new_name='info',
        ),
    ]
