# Generated by Django 4.2.1 on 2023-08-05 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_rename_nombre_infotratacolmena_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infotrataestanque',
            old_name='nombre',
            new_name='info',
        ),
        migrations.RemoveField(
            model_name='infotratacolmena',
            name='infotrata_colmenacol',
        ),
        migrations.AlterField(
            model_name='especiepez',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='reportecolmena',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='reporteestanque',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tsensor',
            name='descripcion',
            field=models.TextField(),
        ),
    ]
